### ISSUE TITLE
Unsupported --parallel flag issued

### ISSUE THREAD

**Issue by JorritSalverda** [rust-lang/cmake-rs#143]
I'm trying to build a Lambda function in Rust to write to Kafka using the `rdkafka` crate as follows:

```toml
[dependencies]
rdkafka = { version = "0.28.0", features = ["ssl-vendored", "gssapi-vendored", "libz-static", "cmake-build"] }
```

I'm building it using Docker image `ekidd/rust-musl-builder:1.57.0` with apt-get package `libsasl2-dev` installed before running `cargo build --release --target x86_64-unknown-linux-musl`.

Unfortunately when this crate gets build it adds a `--parallel` flag that's not supported by the `cmake` version in that Docker image. Is there any way to disable this flag or autodetect that it's not supported?

See https://github.com/emk/rust-musl-builder/issues/138 for the issue with more detail on the error.
